export const STARTER_HAIRSTYLES = [
  {
    slug: "soft-layered-cut", name: "Soft Layered Cut", nameZh: "柔和层次长发", presentation: "feminine", category: "Medium to long",
    length: "Long", maintenance: "Medium", tags: ["Face-framing", "Natural volume"],
    summary: "Natural face-framing layers with soft movement and balanced volume.",
    prompt: "long dark-brown hair below the shoulders with a center part, seamless face-framing layers beginning near the cheekbones, soft feathered ends, balanced natural volume, and gentle movement",
    previewImage: "/images/hairstyles/catalog/soft-layered-cut-v1.webp", previewAlt: "AI catalog model wearing a soft long layered haircut",
  },
  {
    slug: "french-bob", name: "French Bob", nameZh: "法式波波头", presentation: "feminine", category: "Chin length",
    length: "Chin", maintenance: "Medium", tags: ["Soft fringe", "Clean outline"],
    summary: "A polished jaw-length shape with a clean outline and an airy French fringe.",
    prompt: "a dark-brown French bob cut at jaw length with a compact rounded silhouette, softly textured perimeter, subtle inward bend at the ends, and a short airy French fringe above the eyebrows",
    previewImage: "/images/hairstyles/catalog/french-bob-v1.webp", previewAlt: "AI catalog model wearing a jaw-length French bob",
  },
  {
    slug: "curtain-bangs", name: "Curtain Bangs", nameZh: "八字刘海", presentation: "feminine", category: "Bangs",
    length: "Medium", maintenance: "Medium", tags: ["Center part", "Cheekbone framing"],
    summary: "Long parted bangs that frame the cheekbones without changing your overall length.",
    prompt: "long airy curtain bangs opening at the center and sweeping symmetrically toward the cheekbones, with soft face-framing pieces and smooth natural dark-brown hair",
    previewImage: "/images/hairstyles/catalog/curtain-bangs-v1.webp", previewAlt: "AI catalog model wearing long center-parted curtain bangs",
  },
  {
    slug: "blunt-bob", name: "Blunt Bob", nameZh: "齐切波波头", presentation: "feminine", category: "Chin length",
    length: "Chin", maintenance: "Medium", tags: ["Blunt line", "Sleek shape"],
    summary: "A precise chin-length bob with a strong, polished perimeter.",
    prompt: "a sleek dark-brown blunt bob cut precisely at chin length, a center part, minimal layering, an even geometric perimeter, and softly tucked-under ends",
    previewImage: "/images/hairstyles/catalog/blunt-bob-v1.webp", previewAlt: "AI catalog model wearing a sleek chin-length blunt bob",
  },
  {
    slug: "long-bob", name: "Long Bob", nameZh: "长波波头", presentation: "feminine", category: "Shoulder length",
    length: "Medium", maintenance: "Low", tags: ["Versatile", "Clean outline"],
    summary: "A versatile shoulder-skimming bob with a clean, softly weighted outline.",
    prompt: "a dark-brown long bob grazing the shoulders, a center part, a clean softly weighted perimeter, subtle invisible layers, and smooth natural movement",
    previewImage: "/images/hairstyles/catalog/long-bob-v1.webp", previewAlt: "AI catalog model wearing a shoulder-skimming long bob",
  },
  {
    slug: "italian-bob", name: "Italian Bob", nameZh: "意式波波头", presentation: "feminine", category: "Chin length",
    length: "Chin", maintenance: "Medium", tags: ["Full volume", "Side sweep"],
    summary: "A luxurious chin-length bob with a full outline and soft side-swept volume.",
    prompt: "a voluminous dark-brown Italian bob at chin length with a deep soft side part, a full rounded silhouette, lightly layered ends, and glossy touchable movement",
    previewImage: "/images/hairstyles/catalog/italian-bob-v1.webp", previewAlt: "AI catalog model wearing a voluminous Italian bob",
  },
  {
    slug: "pixie-cut", name: "Pixie Cut", nameZh: "精灵短发", presentation: "feminine", category: "Short",
    length: "Short", maintenance: "Medium", tags: ["Tapered nape", "Side fringe"],
    summary: "A close, feminine crop with a tapered outline and softly textured fringe.",
    prompt: "a short dark-brown pixie cut with a softly tapered nape and sides, textured crown, and delicate side-swept fringe, neat but not severe",
    previewImage: "/images/hairstyles/catalog/pixie-cut-v1.webp", previewAlt: "AI catalog model wearing a short textured pixie cut",
  },
  {
    slug: "butterfly-cut", name: "Butterfly Cut", nameZh: "蝴蝶层次剪", presentation: "feminine", category: "Long layers",
    length: "Long", maintenance: "Medium", tags: ["Face framing", "Bouncy layers"],
    summary: "Long cascading layers with shorter, airy pieces that open away from the face.",
    prompt: "long dark-brown butterfly layers below the shoulders with a center part, shorter cheekbone and jaw-length face-framing wings, cascading rounded layers, airy volume, and bouncy feathered ends",
    previewImage: "/images/hairstyles/catalog/butterfly-cut-v1.webp", previewAlt: "AI catalog model wearing a long butterfly layered haircut",
  },
  {
    slug: "bixie-cut", name: "Bixie Cut", nameZh: "短波波精灵剪", presentation: "feminine", category: "Short",
    length: "Short", maintenance: "Medium", tags: ["Airy crown", "Soft fringe"],
    summary: "A versatile pixie-bob hybrid with airy layers and softly face-framing length.",
    prompt: "a dark-brown bixie cut with an ear-grazing layered bob-pixie silhouette, bob-like fullness around the ears, a softly tapered nape, an airy crown, and side-swept face-framing pieces",
    previewImage: "/images/hairstyles/catalog/bixie-cut-v1.webp", previewAlt: "AI catalog model wearing an airy layered bixie cut",
  },
  {
    slug: "wolf-cut", name: "Wolf Cut", nameZh: "狼尾层次剪", presentation: "feminine", category: "Medium layers",
    length: "Medium", maintenance: "Medium", tags: ["Layered crown", "Wispy ends"],
    summary: "A modern layered shape with a full crown and tapered, textured lengths.",
    prompt: "a modern shoulder-length dark-brown wolf cut with heavily layered crown volume, curtain-like face framing, shaggy separated mid-lengths, and tapered wispy ends",
    previewImage: "/images/hairstyles/catalog/wolf-cut-v1.webp", previewAlt: "AI catalog model wearing a modern shoulder-length wolf cut",
  },
  {
    slug: "shag-cut", name: "Shag Cut", nameZh: "复古碎层次剪", presentation: "feminine", category: "Medium layers",
    length: "Medium", maintenance: "Medium", tags: ["Full fringe", "Choppy layers"],
    summary: "A textured medium shag with a soft fringe and abundant, wearable movement.",
    prompt: "a shoulder-length dark-brown modern shag with a soft full fringe, abundant choppy layers, textured crown volume, feathered face framing, and airy separated ends",
    previewImage: "/images/hairstyles/catalog/shag-cut-v1.webp", previewAlt: "AI catalog model wearing a textured modern shag cut",
  },
  {
    slug: "hime-cut", name: "Hime Cut", nameZh: "姬发式", presentation: "feminine", category: "Long statement cut",
    length: "Long", maintenance: "High", tags: ["Blunt fringe", "Stepped sides"],
    summary: "A precise long cut with a blunt fringe and graphic cheek-length side panels.",
    prompt: "a sleek long dark-brown hime cut with a precise blunt eyebrow-length fringe, symmetrical cheek-to-jaw-length sidelocks, and much longer straight hair falling behind",
    previewImage: "/images/hairstyles/catalog/hime-cut-v1.webp", previewAlt: "AI catalog model wearing a precise long hime cut",
  },
  {
    slug: "collarbone-cut", name: "Collarbone Cut", nameZh: "锁骨发", presentation: "feminine", category: "Medium length",
    length: "Medium", maintenance: "Low", tags: ["Clavicle length", "Soft perimeter"],
    summary: "A polished clavicle-grazing cut with a softly weighted, versatile outline.",
    prompt: "dark-brown hair ending precisely at the collarbones with a center part, a softly weighted perimeter, subtle long internal layers, and smooth natural movement",
    previewImage: "/images/hairstyles/catalog/collarbone-cut-v1.webp", previewAlt: "AI catalog model wearing a polished collarbone-length cut",
  },
  {
    slug: "shoulder-length-layers", name: "Shoulder-Length Layers", nameZh: "齐肩层次发", presentation: "feminine", category: "Medium layers",
    length: "Medium", maintenance: "Medium", tags: ["Layered ends", "Face framing"],
    summary: "Shoulder-grazing layers with a soft face frame and light, bouncy ends.",
    prompt: "dark-brown shoulder-length hair with visible seamless graduated layers, cheekbone-to-jaw face framing, softly flipped airy ends, and balanced natural volume",
    previewImage: "/images/hairstyles/catalog/shoulder-length-layers-v1.webp", previewAlt: "AI catalog model wearing shoulder-length layered hair",
  },
  {
    slug: "wispy-bangs", name: "Wispy Bangs", nameZh: "空气刘海", presentation: "feminine", category: "Bangs",
    length: "Medium", maintenance: "Medium", tags: ["Airy fringe", "Temple blend"],
    summary: "A feather-light brow-length fringe that softly opens and blends at the temples.",
    prompt: "medium-long dark-brown hair with a light see-through brow-length wispy fringe, separated fine pieces, longer soft temple sections, and a natural polished finish",
    previewImage: "/images/hairstyles/catalog/wispy-bangs-v1.webp", previewAlt: "AI catalog model wearing light see-through wispy bangs",
  },
  {
    slug: "textured-crop", name: "Textured Crop", nameZh: "纹理短碎发", presentation: "masculine", category: "Short",
    length: "Short", maintenance: "Low", tags: ["Forward texture", "Soft taper"],
    summary: "A compact short cut with natural texture and a softly tapered silhouette.",
    prompt: "a short dark-brown textured crop with visibly separated natural texture, compact forward movement, a softly irregular short fringe, low controlled volume, and neatly tapered sides without a skin fade",
    previewImage: "/images/hairstyles/catalog/textured-crop-v1.webp", previewAlt: "AI catalog model wearing a short textured crop",
  },
  {
    slug: "side-part-taper", name: "Side Part with Taper", nameZh: "侧分渐层短发", presentation: "masculine", category: "Short",
    length: "Short", maintenance: "Low", tags: ["Side part", "Professional"],
    summary: "A classic, neat side part with controlled volume and softly tapered sides.",
    prompt: "dark-brown hair with a clearly defined natural side part, controlled combed volume on top, neat direction across the crown, and softly tapered sides with a conservative gradual blend and no skin fade",
    previewImage: "/images/hairstyles/catalog/side-part-taper-v1.webp", previewAlt: "AI catalog model wearing a classic side part with tapered sides",
  },
  {
    slug: "short-quiff", name: "Short Quiff", nameZh: "短款飞机头", presentation: "masculine", category: "Short",
    length: "Short", maintenance: "Medium", tags: ["Front lift", "Soft taper"],
    summary: "A short shape with controlled lift at the front and clean tapered sides.",
    prompt: "a short natural dark-brown quiff with controlled lift at the front, gently swept upward and slightly back, moderate textured volume on top, a compact crown, and clean softly tapered sides",
    previewImage: "/images/hairstyles/catalog/short-quiff-v1.webp", previewAlt: "AI catalog model wearing a short natural quiff",
  },
  {
    slug: "buzz-cut", name: "Buzz Cut", nameZh: "寸头", presentation: "masculine", category: "Very short",
    length: "Short", maintenance: "Low", tags: ["Even crop", "Clean outline"],
    summary: "An even close crop with a natural hairline and a subtle, low-maintenance taper.",
    prompt: "a classic dark-brown buzz cut at approximately a number two guard, uniformly close cropped with a clean natural hairline and a subtle taper at the temples and nape, no skin fade",
    previewImage: "/images/hairstyles/catalog/buzz-cut-v1.webp", previewAlt: "AI catalog model wearing a classic close buzz cut",
  },
  {
    slug: "crew-cut", name: "Crew Cut", nameZh: "平头", presentation: "masculine", category: "Short",
    length: "Short", maintenance: "Low", tags: ["Graduated top", "Soft taper"],
    summary: "A compact athletic cut with a subtly longer front and clean tapered sides.",
    prompt: "a classic dark-brown crew cut with a short graduated top slightly longer at the front, neatly tapered sides and back, a natural hairline, and no skin fade",
    previewImage: "/images/hairstyles/catalog/crew-cut-v1.webp", previewAlt: "AI catalog model wearing a classic crew cut",
  },
  {
    slug: "french-crop", name: "French Crop", nameZh: "法式短碎发", presentation: "masculine", category: "Short fringe",
    length: "Short", maintenance: "Low", tags: ["Forward texture", "Short fringe"],
    summary: "A short forward-textured crop with a softly broken horizontal fringe.",
    prompt: "a dark-brown French crop with a short separated textured top directed forward, a defined softly irregular fringe, and clean low-tapered sides",
    previewImage: "/images/hairstyles/catalog/french-crop-v1.webp", previewAlt: "AI catalog model wearing a textured French crop",
  },
  {
    slug: "caesar-cut", name: "Caesar Cut", nameZh: "凯撒头", presentation: "masculine", category: "Short fringe",
    length: "Short", maintenance: "Low", tags: ["Even layers", "Blunt fringe"],
    summary: "A classic compact cut with short forward layers and a neat horizontal fringe.",
    prompt: "a classic dark-brown Caesar cut with short even layers combed forward, a small straight horizontal fringe, and conservative softly tapered sides",
    previewImage: "/images/hairstyles/catalog/caesar-cut-v1.webp", previewAlt: "AI catalog model wearing a classic Caesar cut",
  },
  {
    slug: "ivy-league", name: "Ivy League", nameZh: "常春藤短发", presentation: "masculine", category: "Classic short",
    length: "Short", maintenance: "Medium", tags: ["Side part", "Scissor taper"],
    summary: "A refined short cut with enough top length for a tidy natural side part.",
    prompt: "a classic dark-brown Ivy League haircut with a neat side-parted top around four to five centimeters, softly lifted front, and low scissor-tapered sides",
    previewImage: "/images/hairstyles/catalog/ivy-league-v1.webp", previewAlt: "AI catalog model wearing a classic Ivy League haircut",
  },
  { slug: "undercut", name: "Undercut", nameZh: "底削发型", presentation: "masculine", category: "Disconnected", length: "Short", maintenance: "Medium", tags: ["Long top", "Short sides"], summary: "A longer swept top set against distinctly short sides.", prompt: "a classic dark-brown disconnected undercut with a longer swept-back top, short clippered sides, a visible clean disconnection, and no skin fade", previewImage: "/images/hairstyles/catalog/undercut-v1.webp", previewAlt: "AI catalog model wearing a classic disconnected undercut" },
  { slug: "two-block", name: "Two Block", nameZh: "两段式短发", presentation: "masculine", category: "Medium top", length: "Medium", maintenance: "Medium", tags: ["Curtain fringe", "Compact sides"], summary: "A rounded longer top with an airy fringe and compact hidden side sections.", prompt: "a Korean dark-brown two-block haircut with a longer rounded top, airy center-parted fringe, distinctly shorter hair around the ears, and controlled natural volume", previewImage: "/images/hairstyles/catalog/two-block-v1.webp", previewAlt: "AI catalog model wearing a Korean two-block haircut" },
  { slug: "curtains", name: "Curtains", nameZh: "窗帘中分", presentation: "masculine", category: "Medium fringe", length: "Medium", maintenance: "Medium", tags: ["Center part", "Face framing"], summary: "A center-parted medium fringe that sweeps away symmetrically from the face.", prompt: "medium-length dark-brown curtains with a strong center part, symmetrical front panels sweeping away from the forehead, and softly tapered sides", previewImage: "/images/hairstyles/catalog/curtains-v1.webp", previewAlt: "AI catalog model wearing a medium curtain hairstyle" },
  { slug: "middle-part", name: "Middle Part", nameZh: "自然中分", presentation: "masculine", category: "Medium top", length: "Medium", maintenance: "Medium", tags: ["Center part", "Controlled flow"], summary: "A neat medium-length center part with smooth, balanced direction.", prompt: "a neat dark-brown middle-part hairstyle with medium-short top length, precise center separation, controlled low volume, and tidy tapered sides", previewImage: "/images/hairstyles/catalog/middle-part-v1.webp", previewAlt: "AI catalog model wearing a neat middle-part hairstyle" },
  { slug: "comb-over-taper", name: "Comb-Over Taper", nameZh: "侧梳渐层", presentation: "masculine", category: "Classic short", length: "Short", maintenance: "Medium", tags: ["Side sweep", "Low taper"], summary: "A polished side-swept top with a natural part and softly tapered outline.", prompt: "a dark-brown comb-over taper with a defined natural side part, longer top smoothly swept across with controlled volume, and low softly tapered sides", previewImage: "/images/hairstyles/catalog/comb-over-taper-v1.webp", previewAlt: "AI catalog model wearing a comb-over taper" },
  { slug: "modern-mullet", name: "Modern Mullet", nameZh: "现代鲻鱼头", presentation: "masculine", category: "Statement cut", length: "Medium", maintenance: "Medium", tags: ["Textured top", "Longer nape"], summary: "A wearable modern mullet with compact sides and a visibly longer layered back.", prompt: "a modern dark-brown mullet with short textured top and temples, compact sides around the ears, and a visibly longer softly feathered nape", previewImage: "/images/hairstyles/catalog/modern-mullet-v1.webp", previewAlt: "AI catalog model wearing a wearable modern mullet" },
  { slug: "faux-hawk", name: "Faux Hawk", nameZh: "仿莫西干", presentation: "masculine", category: "Textured short", length: "Short", maintenance: "High", tags: ["Central lift", "Tapered sides"], summary: "A subtle central ridge with textured lift and clean short sides.", prompt: "a wearable dark-brown faux hawk with textured top directed upward toward a subtle central ridge, shorter tapered sides, and moderate controlled height", previewImage: "/images/hairstyles/catalog/faux-hawk-v1.webp", previewAlt: "AI catalog model wearing a subtle faux hawk" },
  { slug: "wavy-undercut", name: "Wavy Undercut", nameZh: "波浪底削", presentation: "masculine", category: "Wavy texture", length: "Medium", maintenance: "Medium", tags: ["Defined waves", "Short sides"], summary: "A longer naturally wavy top contrasted with clean, compact sides.", prompt: "a dark-brown wavy undercut with a medium-length top showing loose defined S-waves, swept loosely back, and short disconnected sides", previewImage: "/images/hairstyles/catalog/wavy-undercut-v1.webp", previewAlt: "AI catalog model wearing a naturally wavy undercut" },
  { slug: "beach-waves", name: "Beach Waves", nameZh: "海滩波浪", presentation: "feminine", category: "Waves and texture", length: "Long", maintenance: "Low", tags: ["Loose waves", "Natural texture"], summary: "Relaxed S-waves with airy separation and an effortless finish.", prompt: "long dark-brown hair with relaxed beachy S-waves, a center part, airy separation, softly textured ends, and natural low-shine movement", previewImage: "/images/hairstyles/catalog/beach-waves-v1.webp", previewAlt: "AI catalog model wearing relaxed beach waves" },
  { slug: "loose-curls", name: "Loose Curls", nameZh: "松散卷发", presentation: "feminine", category: "Curls and texture", length: "Long", maintenance: "Medium", tags: ["Soft curls", "Full movement"], summary: "Large, soft curls with polished definition and touchable movement.", prompt: "long dark-brown hair styled in large loose curls with soft definition, balanced volume, a center part, and touchable polished movement", previewImage: "/images/hairstyles/catalog/loose-curls-v1.webp", previewAlt: "AI catalog model wearing long loose curls" },
  { slug: "defined-curls", name: "Defined Curls", nameZh: "清晰卷发", presentation: "feminine", category: "Curls and texture", length: "Medium", maintenance: "Medium", tags: ["Ringlets", "Defined texture"], summary: "Springy, clearly defined curls shaped into a balanced shoulder-length silhouette.", prompt: "shoulder-length dark-brown hair with clearly defined springy ringlets, even curl clumps, rounded balanced volume, and a soft center part", previewImage: "/images/hairstyles/catalog/defined-curls-v1.webp", previewAlt: "AI catalog model wearing shoulder-length defined curls" },
  { slug: "coily-afro", name: "Coily Afro", nameZh: "紧密卷蓬发", presentation: "feminine", category: "Coils and texture", length: "Medium", maintenance: "Medium", tags: ["Coily texture", "Rounded shape"], summary: "A softly rounded natural silhouette that celebrates dense, defined coils.", prompt: "natural dark coily hair shaped into a softly rounded medium afro, dense defined coils, balanced volume, a neat perimeter, and no straightened sections", previewImage: "/images/hairstyles/catalog/coily-afro-v1.webp", previewAlt: "AI catalog model wearing a softly rounded coily afro" },
  { slug: "wet-look-waves", name: "Wet-Look Waves", nameZh: "湿发波浪", presentation: "feminine", category: "Styled texture", length: "Medium", maintenance: "High", tags: ["Glossy finish", "Sculpted waves"], summary: "Glossy, sculpted waves with a sleek editorial finish that stays wearable.", prompt: "shoulder-length dark-brown wet-look waves with glossy defined S-curves, controlled roots, a clean center part, and separated damp-textured ends", previewImage: "/images/hairstyles/catalog/wet-look-waves-v1.webp", previewAlt: "AI catalog model wearing glossy wet-look waves" },
  { slug: "sleek-ponytail", name: "Sleek Ponytail", nameZh: "光滑高马尾", presentation: "feminine", category: "Upstyles", length: "Long", maintenance: "Medium", tags: ["Clean finish", "High ponytail"], summary: "A smooth high ponytail with a clean hairline and polished silhouette.", prompt: "long dark hair pulled into a sleek high ponytail, smooth controlled roots, clean center alignment, a polished hairline, and no loose fringe", previewImage: "/images/hairstyles/catalog/sleek-ponytail-v1.webp", previewAlt: "AI catalog model wearing a sleek high ponytail" },
  { slug: "high-bun", name: "High Bun", nameZh: "高发髻", presentation: "feminine", category: "Upstyles", length: "Long", maintenance: "Medium", tags: ["Top knot", "Polished"], summary: "A polished high bun with smooth roots and a balanced, elegant shape.", prompt: "long dark hair gathered into a polished high bun at the crown, smooth controlled roots, a balanced rounded knot, and a clean hairline", previewImage: "/images/hairstyles/catalog/high-bun-v1.webp", previewAlt: "AI catalog model wearing a polished high bun" },
  { slug: "low-chignon", name: "Low Chignon", nameZh: "低盘发", presentation: "feminine", category: "Upstyles", length: "Long", maintenance: "High", tags: ["Low bun", "Elegant finish"], summary: "A refined low chignon with softly controlled face framing and a neat finish.", prompt: "dark hair arranged in a refined low chignon at the nape, a clean soft side part, smooth roots, subtle face-framing pieces, and an elegant compact shape", previewImage: "/images/hairstyles/catalog/low-chignon-v1.webp", previewAlt: "AI catalog model wearing an elegant low chignon" },
  { slug: "crown-braid", name: "Crown Braid", nameZh: "皇冠编发", presentation: "feminine", category: "Braids and upstyles", length: "Long", maintenance: "High", tags: ["Halo braid", "Statement style"], summary: "A dimensional braid wrapped around the head for a soft, elevated silhouette.", prompt: "dark hair styled in a neat dimensional crown braid wrapping around the head like a halo, securely pinned, with a clean soft hairline", previewImage: "/images/hairstyles/catalog/crown-braid-v1.webp", previewAlt: "AI catalog model wearing a dimensional crown braid" },
  { slug: "box-braids", name: "Box Braids", nameZh: "方格辫", presentation: "feminine", category: "Braids", length: "Long", maintenance: "Low", tags: ["Protective style", "Clean parts"], summary: "Long individual braids with clean square parts and a balanced face-framing fall.", prompt: "long natural dark box braids with precise square parting, consistent medium braid size, a center part, and braids arranged away from the eyes", previewImage: "/images/hairstyles/catalog/box-braids-v1.webp", previewAlt: "AI catalog model wearing long box braids" },
  { slug: "curly-fringe", name: "Curly Fringe", nameZh: "卷发刘海", presentation: "masculine", category: "Curly texture", length: "Medium", maintenance: "Medium", tags: ["Curly fringe", "Tapered sides"], summary: "Natural curls directed forward into a soft fringe with compact tapered sides.", prompt: "natural dark curls on a medium-short top directed forward into a soft curly fringe, with compact low-tapered sides and defined curl clumps", previewImage: "/images/hairstyles/catalog/curly-fringe-v1.webp", previewAlt: "AI catalog model wearing a natural curly fringe" },
  { slug: "textured-pompadour", name: "Textured Pompadour", nameZh: "纹理庞巴度", presentation: "masculine", category: "Volume", length: "Medium", maintenance: "High", tags: ["Front volume", "Textured finish"], summary: "A lifted front with visible texture and a controlled taper for a modern pompadour.", prompt: "a modern dark-brown textured pompadour with strong but wearable front lift, visible separated texture, a compact crown, and clean softly tapered sides", previewImage: "/images/hairstyles/catalog/textured-pompadour-v1.webp", previewAlt: "AI catalog model wearing a textured pompadour" },
  { slug: "natural-afro", name: "Natural Afro", nameZh: "自然蓬发", presentation: "masculine", category: "Coily texture", length: "Medium", maintenance: "Medium", tags: ["Natural coils", "Rounded shape"], summary: "A balanced rounded shape that preserves natural coily texture and density.", prompt: "natural dark tightly coiled hair shaped into a balanced medium afro, rounded silhouette, even density, a clean natural hairline, and no fade", previewImage: "/images/hairstyles/catalog/natural-afro-v1.webp", previewAlt: "AI catalog model wearing a rounded natural afro" },
  { slug: "curly-taper", name: "Curly Taper", nameZh: "卷发渐层", presentation: "masculine", category: "Curly texture", length: "Short", maintenance: "Low", tags: ["Natural curls", "Low taper"], summary: "Defined natural curls on top with a clean, subtle taper around the edges.", prompt: "short natural dark curls with defined texture on top, a clean low taper around the temples and nape, and a natural crisp outline without a skin fade", previewImage: "/images/hairstyles/catalog/curly-taper-v1.webp", previewAlt: "AI catalog model wearing a short curly taper" },
  { slug: "man-bun", name: "Man Bun", nameZh: "男士发髻", presentation: "masculine", category: "Upstyles", length: "Long", maintenance: "Medium", tags: ["Tied back", "Clean silhouette"], summary: "Long hair gathered into a compact bun with the face and hairline kept clear.", prompt: "long dark hair pulled back into a compact masculine bun at the upper back of the head, controlled smooth roots, and a clean natural hairline", previewImage: "/images/hairstyles/catalog/man-bun-v1.webp", previewAlt: "AI catalog model wearing a compact man bun" },
  { slug: "slick-back", name: "Slick Back", nameZh: "油头后梳", presentation: "masculine", category: "Styled medium", length: "Medium", maintenance: "High", tags: ["Swept back", "Polished finish"], summary: "A polished swept-back shape with controlled volume and a clean outline.", prompt: "medium dark-brown hair smoothly swept straight back from the face with controlled volume, a polished low-shine finish, and tidy compact sides", previewImage: "/images/hairstyles/catalog/slick-back-v1.webp", previewAlt: "AI catalog model wearing a polished slick-back hairstyle" },
  { slug: "cornrows", name: "Cornrows", nameZh: "贴头辫", presentation: "masculine", category: "Braids", length: "Medium", maintenance: "Low", tags: ["Protective style", "Precise parting"], summary: "Neat straight-back braids with precise parts and a clean, sculpted silhouette.", prompt: "natural dark hair in neat straight-back cornrows with precise symmetrical parting, consistent braid width, and a clean natural hairline", previewImage: "/images/hairstyles/catalog/cornrows-v1.webp", previewAlt: "AI catalog model wearing neat straight-back cornrows" },
  { slug: "male-box-braids", name: "Box Braids", nameZh: "男士方格辫", presentation: "masculine", category: "Braids", length: "Medium", maintenance: "Low", tags: ["Protective style", "Square parts"], summary: "Medium individual braids with clean square sections and balanced face framing.", prompt: "medium-length masculine box braids with clean square parting, consistent braid size, a center part, and braids framing the face without covering the eyes", previewImage: "/images/hairstyles/catalog/male-box-braids-v1.webp", previewAlt: "AI catalog model wearing medium masculine box braids" },
  { slug: "locs", name: "Locs", nameZh: "脏辫", presentation: "masculine", category: "Locs", length: "Medium", maintenance: "Medium", tags: ["Natural texture", "Defined locs"], summary: "Well-groomed medium locs with natural movement and a balanced face-framing shape.", prompt: "well-groomed medium-length natural dark locs with clear individual definition, balanced volume, and locs shaped away from the eyes", previewImage: "/images/hairstyles/catalog/locs-v1.webp", previewAlt: "AI catalog model wearing well-groomed medium locs" },
] as const;

export const STARTER_CATALOG_VERSION = "starter-catalog-v2";
export const STARTER_CATALOG_REVIEW_STATUS = "approved" as const;

export type StarterHairstyleSlug = (typeof STARTER_HAIRSTYLES)[number]["slug"];

export function getStarterHairstyle(slug: string) {
  return STARTER_HAIRSTYLES.find((style) => style.slug === slug);
}
