export const hairstyleCatalog = {
  "beach-waves": { name: "Beach Waves", nameZh: "海滩波浪", category: "texture", length: "long", texture: ["straight", "wavy"], maintenance: "low", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/beach-waves-v1.webp" },
  "loose-curls": { name: "Loose Curls", nameZh: "松散卷发", category: "texture", length: "long", texture: ["wavy", "curly"], maintenance: "medium", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/loose-curls-v1.webp" },
  "defined-curls": { name: "Defined Curls", nameZh: "清晰卷发", category: "texture", length: "medium", texture: ["curly"], maintenance: "medium", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/defined-curls-v1.webp" },
  "coily-afro": { name: "Coily Afro", nameZh: "紧密卷蓬发", category: "texture", length: "medium", texture: ["coily"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/coily-afro-v1.webp" },
  "wet-look-waves": { name: "Wet-Look Waves", nameZh: "湿发波浪", category: "texture", length: "medium", texture: ["straight", "wavy", "curly"], maintenance: "high", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/wet-look-waves-v1.webp" },
  "sleek-ponytail": { name: "Sleek Ponytail", nameZh: "光滑高马尾", category: "upstyle", length: "long", texture: ["straight", "wavy", "curly", "coily"], maintenance: "medium", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/sleek-ponytail-v1.webp" },
  "high-bun": { name: "High Bun", nameZh: "高发髻", category: "upstyle", length: "long", texture: ["straight", "wavy", "curly", "coily"], maintenance: "medium", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/high-bun-v1.webp" },
  "low-chignon": { name: "Low Chignon", nameZh: "低盘发", category: "upstyle", length: "long", texture: ["straight", "wavy"], maintenance: "high", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/low-chignon-v1.webp" },
  "crown-braid": { name: "Crown Braid", nameZh: "皇冠编发", category: "braids", length: "long", texture: ["straight", "wavy", "curly", "coily"], maintenance: "high", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/crown-braid-v1.webp" },
  "box-braids": { name: "Box Braids", nameZh: "方格辫", category: "braids", length: "long", texture: ["curly", "coily"], maintenance: "low", minHairLength: "short", preview: "/images/hairstyles/catalog/box-braids-v1.webp" },
  "curly-fringe": { name: "Curly Fringe", nameZh: "卷发刘海", category: "texture", length: "medium", texture: ["curly", "coily"], maintenance: "medium", minHairLength: "brow", preview: "/images/hairstyles/catalog/curly-fringe-v1.webp" },
  "textured-pompadour": { name: "Textured Pompadour", nameZh: "纹理庞巴度", category: "volume", length: "medium", texture: ["straight", "wavy", "curly"], maintenance: "high", minHairLength: "brow", preview: "/images/hairstyles/catalog/textured-pompadour-v1.webp" },
  "natural-afro": { name: "Natural Afro", nameZh: "自然蓬发", category: "texture", length: "medium", texture: ["coily"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/natural-afro-v1.webp" },
  "curly-taper": { name: "Curly Taper", nameZh: "卷发渐层", category: "texture", length: "short", texture: ["curly", "coily"], maintenance: "low", minHairLength: "short", preview: "/images/hairstyles/catalog/curly-taper-v1.webp" },
  "man-bun": { name: "Man Bun", nameZh: "男士发髻", category: "upstyle", length: "long", texture: ["straight", "wavy", "curly", "coily"], maintenance: "medium", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/man-bun-v1.webp" },
  "slick-back": { name: "Slick Back", nameZh: "油头后梳", category: "styled", length: "medium", texture: ["straight", "wavy"], maintenance: "high", minHairLength: "brow", preview: "/images/hairstyles/catalog/slick-back-v1.webp" },
  "cornrows": { name: "Cornrows", nameZh: "贴头辫", category: "braids", length: "medium", texture: ["curly", "coily"], maintenance: "low", minHairLength: "short", preview: "/images/hairstyles/catalog/cornrows-v1.webp" },
  "male-box-braids": { name: "Box Braids", nameZh: "男士方格辫", category: "braids", length: "medium", texture: ["curly", "coily"], maintenance: "low", minHairLength: "short", preview: "/images/hairstyles/catalog/male-box-braids-v1.webp" },
  "locs": { name: "Locs", nameZh: "脏辫", category: "locs", length: "medium", texture: ["curly", "coily"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/locs-v1.webp" },
  "comb-over-taper": { name: "Comb-Over Taper", nameZh: "侧梳渐层", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/comb-over-taper-v1.webp" },
  "modern-mullet": { name: "Modern Mullet", nameZh: "现代鲻鱼头", category: "statement", length: "medium", texture: ["straight", "wavy", "curly"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/modern-mullet-v1.webp" },
  "faux-hawk": { name: "Faux Hawk", nameZh: "仿莫西干", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "high", minHairLength: "short", preview: "/images/hairstyles/catalog/faux-hawk-v1.webp" },
  "wavy-undercut": { name: "Wavy Undercut", nameZh: "波浪底削", category: "texture", length: "medium", texture: ["wavy"], maintenance: "medium", minHairLength: "brow", preview: "/images/hairstyles/catalog/wavy-undercut-v1.webp" },
  "undercut": { name: "Undercut", nameZh: "底削发型", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/undercut-v1.webp" },
  "two-block": { name: "Two Block", nameZh: "两段式短发", category: "medium", length: "medium", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/two-block-v1.webp" },
  "curtains": { name: "Curtains", nameZh: "窗帘中分", category: "medium", length: "medium", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "brow", preview: "/images/hairstyles/catalog/curtains-v1.webp" },
  "middle-part": { name: "Middle Part", nameZh: "自然中分", category: "medium", length: "medium", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "brow", preview: "/images/hairstyles/catalog/middle-part-v1.webp" },
  "crew-cut": { name: "Crew Cut", nameZh: "平头", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "low", minHairLength: "short", preview: "/images/hairstyles/catalog/crew-cut-v1.webp" },
  "french-crop": { name: "French Crop", nameZh: "法式短碎发", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "low", minHairLength: "short", preview: "/images/hairstyles/catalog/french-crop-v1.webp" },
  "caesar-cut": { name: "Caesar Cut", nameZh: "凯撒头", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "low", minHairLength: "short", preview: "/images/hairstyles/catalog/caesar-cut-v1.webp" },
  "ivy-league": { name: "Ivy League", nameZh: "常春藤短发", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/ivy-league-v1.webp" },
  "collarbone-cut": { name: "Collarbone Cut", nameZh: "锁骨发", category: "medium", length: "medium", texture: ["straight", "wavy"], maintenance: "low", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/collarbone-cut-v1.webp" },
  "shoulder-length-layers": { name: "Shoulder-Length Layers", nameZh: "齐肩层次发", category: "layers", length: "medium", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/shoulder-length-layers-v1.webp" },
  "wispy-bangs": { name: "Wispy Bangs", nameZh: "空气刘海", category: "bangs", length: "medium", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "brow", preview: "/images/hairstyles/catalog/wispy-bangs-v1.webp" },
  "buzz-cut": { name: "Buzz Cut", nameZh: "寸头", category: "short", length: "short", texture: ["straight", "wavy", "curly", "coily"], maintenance: "low", minHairLength: "short", preview: "/images/hairstyles/catalog/buzz-cut-v1.webp" },
  "bixie-cut": { name: "Bixie Cut", nameZh: "短波波精灵剪", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/bixie-cut-v1.webp" },
  "wolf-cut": { name: "Wolf Cut", nameZh: "狼尾层次剪", category: "layers", length: "medium", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/wolf-cut-v1.webp" },
  "shag-cut": { name: "Shag Cut", nameZh: "复古碎层次剪", category: "layers", length: "medium", texture: ["straight", "wavy", "curly"], maintenance: "medium", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/shag-cut-v1.webp" },
  "hime-cut": { name: "Hime Cut", nameZh: "姬发式", category: "statement", length: "long", texture: ["straight"], maintenance: "high", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/hime-cut-v1.webp" },
  "blunt-bob": { name: "Blunt Bob", nameZh: "齐切波波头", category: "bob", length: "chin", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "jaw", preview: "/images/hairstyles/catalog/blunt-bob-v1.webp" },
  "long-bob": { name: "Long Bob", nameZh: "长波波头", category: "bob", length: "medium", texture: ["straight", "wavy"], maintenance: "low", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/long-bob-v1.webp" },
  "italian-bob": { name: "Italian Bob", nameZh: "意式波波头", category: "bob", length: "chin", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "jaw", preview: "/images/hairstyles/catalog/italian-bob-v1.webp" },
  "pixie-cut": { name: "Pixie Cut", nameZh: "精灵短发", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/pixie-cut-v1.webp" },
  "butterfly-cut": { name: "Butterfly Cut", nameZh: "蝴蝶层次剪", category: "layers", length: "long", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/butterfly-cut-v1.webp" },
  "soft-layered-cut": { name: "Soft Layered Cut", nameZh: "柔和层次长发", category: "layers", length: "long", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "shoulder", preview: "/images/hairstyles/catalog/soft-layered-cut-v1.webp" },
  "french-bob": { name: "French Bob", nameZh: "法式波波头", category: "bob", length: "chin", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "jaw", preview: "/images/hairstyles/catalog/french-bob-v1.webp" },
  "curtain-bangs": { name: "Curtain Bangs", nameZh: "八字刘海", category: "bangs", length: "medium", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "cheekbone", preview: "/images/hairstyles/catalog/curtain-bangs-v1.webp" },
  "textured-crop": { name: "Textured Crop", nameZh: "纹理短碎发", category: "short", length: "short", texture: ["straight", "wavy", "curly"], maintenance: "low", minHairLength: "short", preview: "/images/hairstyles/catalog/textured-crop-v1.webp" },
  "side-part-taper": { name: "Side Part with Taper", nameZh: "侧分渐层短发", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "low", minHairLength: "short", preview: "/images/hairstyles/catalog/side-part-taper-v1.webp" },
  "short-quiff": { name: "Short Quiff", nameZh: "短款飞机头", category: "short", length: "short", texture: ["straight", "wavy"], maintenance: "medium", minHairLength: "short", preview: "/images/hairstyles/catalog/short-quiff-v1.webp" },
} as const;

export const previewMetadata = {
  previewPromptVersion: "catalog-preview-v1",
  previewModel: "openai-imagegen-built-in",
  reviewStatus: "approved" as const,
};

export function catalogDocument(slug: keyof typeof hairstyleCatalog) {
  const style = hairstyleCatalog[slug];
  return {
    slug,
    nameEn: style.name,
    nameZh: style.nameZh,
    gender: "unisex",
    category: style.category,
    length: style.length,
    texture: [...style.texture],
    maintenanceLevel: style.maintenance,
    requiresPerm: false,
    requiresColor: false,
    minHairLength: style.minHairLength,
    recommendedFaceShapes: [] as string[],
    notRecommendedFaceShapes: [] as string[],
    recommendedDensity: [] as string[],
    recommendedTexture: [] as string[],
    referenceImages: [] as string[],
    previewImages: [style.preview],
    ...previewMetadata,
    promptTemplate: slug,
    active: true,
  };
}
