import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

const timestamp = { createdAt: v.number(), updatedAt: v.optional(v.number()) };

export default defineSchema({
  hairstylePolls: defineTable({ userId: v.id("users"), token: v.string(), active: v.boolean(), title: v.string(), resultIds: v.array(v.id("generationResults")), totals: v.array(v.number()), counts: v.array(v.number()), ...timestamp }).index("by_token", ["token"]).index("by_user", ["userId"]),
  pollRatings: defineTable({ pollId: v.id("hairstylePolls"), voterId: v.string(), scores: v.array(v.number()), ...timestamp }).index("by_poll_voter", ["pollId", "voterId"]),
  ratingLimits: defineTable({ key: v.string(), windowStart: v.number(), used: v.number() }).index("by_key", ["key"]).index("by_window", ["windowStart"]),
  generationQuotas: defineTable({ userId: v.id("users"), dayStart: v.number(), used: v.number() }).index("by_user_day", ["userId", "dayStart"]),
  resultShares: defineTable({ userId: v.id("users"), generationResultId: v.id("generationResults"), token: v.string(), active: v.boolean(), ratingCount: v.number(), ratingTotal: v.number(), ...timestamp }).index("by_token", ["token"]).index("by_result", ["generationResultId"]),
  shareRatings: defineTable({ shareId: v.id("resultShares"), voterId: v.string(), score: v.number(), ...timestamp }).index("by_share_voter", ["shareId", "voterId"]),
  users: defineTable({ clerkId: v.string(), email: v.optional(v.string()), displayName: v.optional(v.string()), locale: v.string(), credits: v.number(), ...timestamp }).index("by_clerk_id", ["clerkId"]),
  userProfiles: defineTable({ userId: v.id("users"), genderPreference: v.optional(v.union(v.literal("female"), v.literal("male"), v.literal("unisex"))), maintenancePreference: v.optional(v.union(v.literal("low"), v.literal("medium"), v.literal("high"))), ...timestamp }).index("by_user", ["userId"]),
  uploads: defineTable({ userId: v.id("users"), type: v.union(v.literal("original"), v.literal("reference"), v.literal("side")), r2Key: v.string(), mimeType: v.string(), size: v.number(), width: v.optional(v.number()), height: v.optional(v.number()), ...timestamp }).index("by_user", ["userId"]).index("by_r2_key", ["r2Key"]),
  faceAnalyses: defineTable({ userId: v.id("users"), uploadId: v.id("uploads"), faceShape: v.string(), confidence: v.number(), foreheadHeight: v.string(), foreheadWidth: v.string(), cheekboneWidth: v.string(), jawWidth: v.string(), jawSharpness: v.string(), chinShape: v.string(), faceLength: v.string(), ...timestamp }).index("by_upload", ["uploadId"]),
  hairAnalyses: defineTable({ userId: v.id("users"), uploadId: v.id("uploads"), hairLength: v.string(), hairDensity: v.string(), texture: v.string(), thickness: v.string(), hairline: v.string(), crownVolume: v.string(), ...timestamp }).index("by_upload", ["uploadId"]),
  hairstyles: defineTable({ slug: v.string(), nameEn: v.string(), nameZh: v.string(), aliasesEn: v.optional(v.array(v.string())), aliasesZh: v.optional(v.array(v.string())), gender: v.string(), category: v.string(), length: v.string(), texture: v.array(v.string()), bangType: v.optional(v.string()), layerType: v.optional(v.string()), volume: v.optional(v.string()), maintenanceLevel: v.string(), requiresPerm: v.boolean(), requiresColor: v.boolean(), minHairLength: v.string(), recommendedFaceShapes: v.array(v.string()), notRecommendedFaceShapes: v.array(v.string()), recommendedDensity: v.array(v.string()), recommendedTexture: v.array(v.string()), referenceImages: v.array(v.string()), previewImages: v.optional(v.array(v.string())), previewPromptVersion: v.optional(v.string()), previewModel: v.optional(v.string()), reviewStatus: v.optional(v.union(v.literal("draft"), v.literal("approved"), v.literal("retired"))), promptTemplate: v.string(), active: v.boolean(), ...timestamp }).index("by_slug", ["slug"]),
  recommendations: defineTable({ userId: v.id("users"), uploadId: v.id("uploads"), hairstyleId: v.id("hairstyles"), rank: v.number(), matchReason: v.string(), maintenanceLevel: v.string(), feasibility: v.string(), requiresPerm: v.boolean(), requiresColor: v.boolean(), ...timestamp }).index("by_user_upload", ["userId", "uploadId"]),
  generations: defineTable({ userId: v.id("users"), uploadId: v.id("uploads"), hairstyleId: v.id("hairstyles"), referenceUploadId: v.optional(v.id("uploads")), provider: v.string(), model: v.string(), promptVersion: v.string(), status: v.union(v.literal("queued"), v.literal("processing"), v.literal("completed"), v.literal("failed")), creditsUsed: v.number(), generationTimeMs: v.optional(v.number()), errorCode: v.optional(v.string()), ...timestamp }).index("by_user", ["userId"]).index("by_status", ["status"]).index("by_user_created", ["userId", "createdAt"]),
  generationResults: defineTable({ generationId: v.id("generations"), r2Key: v.string(), view: v.optional(v.union(v.literal("front"), v.literal("side"))), faceSimilarity: v.optional(v.number()), identityPassed: v.optional(v.boolean()), selected: v.boolean(), ...timestamp }).index("by_generation", ["generationId"]),
  favorites: defineTable({ userId: v.id("users"), generationResultId: v.id("generationResults"), ...timestamp }).index("by_user", ["userId"]),
  stylistGuides: defineTable({ userId: v.id("users"), generationResultId: v.id("generationResults"), hairstyleId: v.id("hairstyles"), feasibilityLevel: v.string(), feasibilityReason: v.string(), instructions: v.object({ length: v.string(), front: v.string(), bangs: v.string(), crown: v.string(), back: v.string(), thinning: v.string(), styling: v.string(), perm: v.string(), color: v.string() }), dailyStylingMinutes: v.number(), maintenanceWeeks: v.number(), ...timestamp }).index("by_user", ["userId"]),
  creditTransactions: defineTable({ userId: v.id("users"), amount: v.number(), balanceAfter: v.number(), reason: v.string(), relatedGenerationId: v.optional(v.id("generations")), relatedOrderId: v.optional(v.id("orders")), idempotencyKey: v.string(), ...timestamp }).index("by_user", ["userId"]).index("by_idempotency", ["idempotencyKey"]),
  orders: defineTable({ userId: v.id("users"), provider: v.string(), providerOrderId: v.string(), productId: v.string(), amount: v.number(), currency: v.string(), status: v.string(), creditsGranted: v.number(), ...timestamp }).index("by_provider_order", ["provider", "providerOrderId"]),
  promptTemplates: defineTable({ taskType: v.string(), provider: v.string(), version: v.string(), systemPrompt: v.string(), userPromptTemplate: v.string(), active: v.boolean(), ...timestamp }).index("by_task_provider", ["taskType", "provider"]),
  modelUsage: defineTable({ userId: v.id("users"), generationId: v.optional(v.id("generations")), provider: v.string(), model: v.string(), taskType: v.string(), durationMs: v.number(), estimatedCostUsd: v.optional(v.number()), status: v.string(), providerRequestId: v.optional(v.string()), ...timestamp }).index("by_generation", ["generationId"]),
});
